name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force
          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          
          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389
          # (Optional) Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Create User
        run: |
          New-LocalUser -Name "plsmeow" -Password "plsmeow" -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "plsmeow"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "plsmeow"
          
          echo "RDP_CREDS=User: plsmeow | Password: plsmeow" >> $env:GITHUB_ENV
          
          if (-not (Get-LocalUser -Name "plsmeow")) {
              Write-Error "User creation failed"
              exit 1
          }

      - name: SSH Tunnel 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: SSH Tunnel with key
        run: ssh -N -R 3389:localhost:3389 plsmeow@195.133.146.20

      - name: Connection
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: 195.133.146.20"
          Write-Host "Username: plsmeow"
          Write-Host "Password: plsmeow"
          Write-Host "==================`n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
